// Copyright 2026 kirzo

#include "K2Node_PlayDialogueLine.h"

#include "KzDialogueAsset.h"
#include "KzDialogueFunctionLibrary.h"
#include "KzDialogueTypes.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "K2Node_MakeStruct.h"
#include "KismetCompiler.h"
#include "Kismet2/BlueprintEditorUtils.h"

#include "GameplayTagContainer.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_PlayDialogueLine"

const FName UK2Node_PlayDialogueLine::PN_Asset = TEXT("Asset");
const FName UK2Node_PlayDialogueLine::PN_LineId = TEXT("LineId");
const FName UK2Node_PlayDialogueLine::PN_Channel = TEXT("Channel");
const FName UK2Node_PlayDialogueLine::PN_Priority = TEXT("Priority");
const FName UK2Node_PlayDialogueLine::PN_StartImmediately = TEXT("bStartImmediately");
const FName UK2Node_PlayDialogueLine::PN_WorldContext = TEXT("__WorldContext");
const FName UK2Node_PlayDialogueLine::PN_ReturnValue = TEXT("ReturnValue");

// =======================================================================================
// Pin layout
// =======================================================================================

void UK2Node_PlayDialogueLine::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* K2 = GetDefault<UEdGraphSchema_K2>();

	// Exec pins.
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	// Asset (always connectable).
	UEdGraphPin* AssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object,
		UKzDialogueAsset::StaticClass(), PN_Asset);
	AssetPin->PinFriendlyName = LOCTEXT("AssetPin", "Asset");

	// LineId — typed as FGuid struct, always connectable. The pin factory in the
	// editor module replaces its default widget with the dropdown when appropriate.
	UEdGraphPin* LineIdPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct,
		TBaseStructure<FGuid>::Get(), PN_LineId);
	LineIdPin->PinFriendlyName = LOCTEXT("LineIdPin", "Line");

	// Channel.
	UEdGraphPin* ChannelPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct,
		TBaseStructure<FGameplayTag>::Get(), PN_Channel);
	ChannelPin->PinFriendlyName = LOCTEXT("ChannelPin", "Channel");
	K2->SetPinAutogeneratedDefaultValue(ChannelPin, TEXT("Dialogue.Channel.Main"));

	// Priority (advanced).
	UEdGraphPin* PriorityPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, PN_Priority);
	K2->SetPinAutogeneratedDefaultValue(PriorityPin, TEXT("-1"));
	PriorityPin->bAdvancedView = true;

	// StartImmediately (advanced).
	UEdGraphPin* StartPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, PN_StartImmediately);
	K2->SetPinAutogeneratedDefaultValue(StartPin, TEXT("true"));
	StartPin->bAdvancedView = true;

	// World context (hidden).
	UEdGraphPin* WorldPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object,
		UObject::StaticClass(), PN_WorldContext);
	WorldPin->bHidden = true;

	// Return value.
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Object,
		FindObject<UClass>(nullptr, TEXT("/Script/KzDialogue.KzDialoguePlayer")), PN_ReturnValue);

	if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
	{
		AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
	}

	Super::AllocateDefaultPins();
}

// =======================================================================================
// Cosmetics
// =======================================================================================

FText UK2Node_PlayDialogueLine::GetNodeTitle(ENodeTitleType::Type /*TitleType*/) const
{
	return LOCTEXT("NodeTitle", "Play Dialogue Line");
}

FText UK2Node_PlayDialogueLine::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Plays a single line from a Dialogue Asset.\n"
		"When the Asset pin is unconnected and a literal asset is selected, the Line "
		"pin shows a dropdown of the asset's lines. When the Asset pin is connected "
		"at runtime, you must provide the Line GUID via the LineId pin.");
}

FSlateIcon UK2Node_PlayDialogueLine::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = FLinearColor(0.29f, 0.43f, 0.71f); // Match the dialogue asset color.
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Icons.Comment");
}

// =======================================================================================
// Reactions
// =======================================================================================

void UK2Node_PlayDialogueLine::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);

	if (Pin == GetAssetPin())
	{
		// The pin factory's widget reads ShouldShowLineDropdown() so a refresh is enough.
		GetGraph()->NotifyGraphChanged();
	}
}

void UK2Node_PlayDialogueLine::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetAssetPin())
	{
		// Literal asset changed: the dropdown's option list depends on it.
		GetGraph()->NotifyGraphChanged();
	}
}

// =======================================================================================
// Menu registration
// =======================================================================================

void UK2Node_PlayDialogueLine::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_PlayDialogueLine::GetMenuCategory() const
{
	return LOCTEXT("MenuCategory", "Dialogue");
}

// =======================================================================================
// Pin accessors
// =======================================================================================

UEdGraphPin* UK2Node_PlayDialogueLine::GetAssetPin() const { return FindPin(PN_Asset); }
UEdGraphPin* UK2Node_PlayDialogueLine::GetLineIdPin() const { return FindPin(PN_LineId); }

bool UK2Node_PlayDialogueLine::ShouldShowLineDropdown() const
{
	const UEdGraphPin* AssetPin = GetAssetPin();
	if (!AssetPin || AssetPin->LinkedTo.Num() > 0) { return false; }
	return GetLiteralAsset() != nullptr;
}

UKzDialogueAsset* UK2Node_PlayDialogueLine::GetLiteralAsset() const
{
	const UEdGraphPin* AssetPin = GetAssetPin();
	if (!AssetPin || AssetPin->LinkedTo.Num() > 0) { return nullptr; }
	return Cast<UKzDialogueAsset>(AssetPin->DefaultObject);
}

FGuid UK2Node_PlayDialogueLine::GetLineIdValue() const
{
	const UEdGraphPin* LineIdPin = GetLineIdPin();
	if (!LineIdPin) { return FGuid(); }

	// FGuid struct pin stores its value as a string formatted by FGuid::ToString.
	FGuid LineId;
	FGuid::Parse(LineIdPin->GetDefaultAsString(), LineId);
	return LineId;
}

// =======================================================================================
// Compilation: expand to a function call
// =======================================================================================

void UK2Node_PlayDialogueLine::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* AssetPin = GetAssetPin();
	const bool bAssetIsLiteral = AssetPin && AssetPin->LinkedTo.Num() == 0;

	// Common helper: build a CallFunction node and route the standard pins.
	auto BuildCall = [&](FName FunctionName) -> UK2Node_CallFunction*
		{
			UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
			Call->FunctionReference.SetExternalMember(FunctionName, UKzDialogueFunctionLibrary::StaticClass());
			Call->AllocateDefaultPins();

			// Wire exec / then.
			CompilerContext.MovePinLinksToIntermediate(*FindPin(UEdGraphSchema_K2::PN_Execute), *Call->GetExecPin());
			CompilerContext.MovePinLinksToIntermediate(*FindPin(UEdGraphSchema_K2::PN_Then), *Call->GetThenPin());

			// Wire return.
			CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_ReturnValue), *Call->GetReturnValuePin());

			// Wire WorldContext (hidden on our node, hidden on the call too — the BP
			// compiler resolves it automatically via the CallFunction's metadata).
			if (UEdGraphPin* CallWorldPin = Call->FindPin(TEXT("WorldContextObject")))
			{
				CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_WorldContext), *CallWorldPin);
			}

			return Call;
		};

	if (bAssetIsLiteral)
	{
		// =============================================================================
		// Literal path: build a transient FKzDialogueLine via MakeStruct, then call
		// PlayDialogueLine directly. Avoids a runtime lookup.
		// =============================================================================
		UKzDialogueAsset* Asset = GetLiteralAsset();
		const FGuid LineId = GetLineIdValue();

		FKzDialogueLine ResolvedLine;
		const bool bResolved = Asset && Asset->TryGetLineById(LineId, ResolvedLine);
		if (!bResolved)
		{
			CompilerContext.MessageLog.Warning(
				*LOCTEXT("UnresolvedLine", "@@: Line GUID could not be resolved in the selected asset.").ToString(), this);
		}

		// Instead of building an FKzDialogueLine literal (which is awkward to do with
		// MakeStruct from Blueprint codegen for nested tags/objects), we route through
		// the runtime helper. It does exactly the same as the runtime path for
		// connected assets: lookup by GUID, then PlayLine.
		//
		// This keeps the literal and dynamic paths identical at runtime, simplifying
		// debugging. The "literal vs dynamic" distinction only affects the editor UX
		// (the dropdown), not the compiled bytecode.
		UK2Node_CallFunction* Call = BuildCall(GET_FUNCTION_NAME_CHECKED(
			UKzDialogueFunctionLibrary, PlayDialogueLineFromAsset));

		// Route Asset (literal default object).
		if (UEdGraphPin* CallAssetPin = Call->FindPin(TEXT("Asset")))
		{
			CallAssetPin->DefaultObject = Asset;
		}

		// Route LineId (literal GUID as default string).
		if (UEdGraphPin* CallLineIdPin = Call->FindPin(TEXT("LineId")))
		{
			// Use EGuidFormats::Digits so the Blueprint compiler's ImportText can parse it natively
			CallLineIdPin->DefaultValue = LineId.ToString(EGuidFormats::Digits);
		}

		// Route Channel / Priority / StartImmediately (regular pin moves).
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_Channel), *Call->FindPin(TEXT("Channel")));
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_Priority), *Call->FindPin(TEXT("Priority")));
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_StartImmediately), *Call->FindPin(TEXT("bStartImmediately")));
	}
	else
	{
		// =============================================================================
		// Dynamic path: Asset pin is connected. Use the runtime helper that does the
		// lookup at runtime.
		// =============================================================================
		UK2Node_CallFunction* Call = BuildCall(GET_FUNCTION_NAME_CHECKED(
			UKzDialogueFunctionLibrary, PlayDialogueLineFromAsset));

		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_Asset), *Call->FindPin(TEXT("Asset")));
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_LineId), *Call->FindPin(TEXT("LineId")));
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_Channel), *Call->FindPin(TEXT("Channel")));
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_Priority), *Call->FindPin(TEXT("Priority")));
		CompilerContext.MovePinLinksToIntermediate(*FindPin(PN_StartImmediately), *Call->FindPin(TEXT("bStartImmediately")));
	}

	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE